spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: 1234
  flyway:
    user: postgres
    password: 1234
    url: r2dbc:postgresql://localhost:5432/spring_reactive