spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/spring_reactive
    username: postgres
    password: 1234
#  flyway:
#    url: jdbc:postgresql://localhost:5433/spring_reactive
#    user: postgres
#    password: 1234
